#!/bin/bash

GH_PAGES_GIT_URL="https://github.com/treasure-data/digdag-docs.git"
GH_PAGES_BRANCH="gh-pages"
CNAME="www.digdag.io"
DOCS_DIR="digdag-docs/build/html"
REVISION="$(git rev-parse HEAD)"
GIT_USER_NAME="Circle CI"
GIT_USER_NAME="circleci@digdag.io"

set -xe

./gradlew site

git fetch --unshallow || echo "Already unshallowed"

# build the docs
rm -rf gh_pages
git clone . gh_pages

# push the docs to the remote git repo
cd gh_pages
git remote add ci-gh-pages "$GH_PAGES_GIT_URL"
git fetch ci-gh-pages
git checkout -b ci-gh-pages ci-gh-pages/$GH_PAGES_BRANCH

cd ..
rm -rf gh_pages/*
cp -a "$DOCS_DIR"/* gh_pages/
cd gh_pages

touch ".nojekyll"
if [ -n "$CNAME" ];then
    echo $CNAME > "CNAME"
fi

git add --all .
git config user.name "$GIT_USER_NAME"
git config user.email "$GIT_USER_EMAIL"
git commit -m "Updated document $REVISION" || echo "Nothing to update"

if ! git show | grep -E '^[+-] ' | grep -Eqv 'Generated by|Generated on|Search.setIndex|meta name="date" content='; then
    echo "No document changes."
    exit 0
fi

git config credential.helper "store --file=$HOME/.git_credentials"

echo "https://$GITHUB_TOKEN:@github.com" > "$HOME/.git_credentials"
trap "rm -rf $HOME/.git_credentials" EXIT

git push ci-gh-pages ci-gh-pages:$GH_PAGES_BRANCH
